name: proteus-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python =3.7.6
  - compilers =1.1.3
  - pip =20.3.3
  - make
  - setuptools =49.6.0
  - cython =0.29.21
  - daetk =1.0.1
  - hdf5 =1.10.6=*mpich*
  - h5py =3.1.0=*mpich*
  - metis =5.1.0
  - mpich =3.3.2
  - numpy =1.19.4
  - openblas =0.3.13
  - parmetis =4.0.3
  - petsc4py =3.13.0
  - petsc =3.13.6
  - scorec =2.2.2
  - superlu =5.2.2
  - superlu_dist =6.2.0
  - triangle =1.6
  - pychrono =5.0.1
  - gmsh
  - matplotlib =3.3.3
  - mpi4py =3.0.3
  - nose
  - pytables =3.6.1
  - pytest
  - pytest-cov
  - pytest-xdist
  - scipy =1.5.3
  - tetgen =1.6.0
  - ncurses =6.2
  - future =0.18.2
  - ipyparallel =6.3.0
  - pillow =8.0.1
  - recordtype =1.3
  - xtensor-python
  - git-lfs
  - eigen =3.3.9
  - zoltan =3.83
  - hypre =2.18.2
  - mumps-mpi =5.2.1
  - numexpr =2.7.1
  - ptscotch =6.0.9
  - scalapack =2.0.2
  - tbb =2020.2
  - zipp =3.4.0
  - parso =0.8.1
  - pycparser =2.20
  - ipython =5.8.0
  - decorator =4.4.2
  - cffi =1.14.4
  - ipygany =0.4.0 
